grails:
  profile: rest-api
  codegen:
    defaultPackage: tidistock
  controllers:
    upload:
      maxFileSize: 26214400
      maxRequestSize: 26214400
    defaultScope: singleton
  cors:
    enabled: true
    allowCredentials: false
    allowedOriginPatterns:
      - "*"
    allowedMethods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowedHeaders:
      - "*"
  gorm:
    reactor:
      # Whether to translate GORM events into Reactor events
      # Disabled by default for performance reasons
      events: false
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      json:
        - application/json
        - text/json
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: '*/*'
  urlmapping:
    cache:
      maxsize: 1000
  converters:
    encoding: UTF-8
  plugin:
    springsecurity:
      userLookup:
        userDomainClassName: 'tidistock.User'
        authorityJoinClassName: 'tidistock.UserRole'
        authorityClassName: 'tidistock.Role'
      password:
        algorithm: 'bcrypt'
      rest:
        token:
          storage:
            jwt:
              secret: 'w0T5HL+qE2yT5zU7W8F8Yw+3A2U5o5BRr5R/Jg1H8W0=' # dev & test
              expiration: 31536000
        login:
          active: true
          endpointUrl: '/tidistock/login'
          useJsonCredentials: true
          usernamePropertyName: 'phone_number'
          passwordPropertyName: 'password'
        logout:
          endpointUrl: '/tidistock/logout'
      filterChain:
        chainMap:
          - pattern: '/api/**'
            filters: 'JOINED_FILTERS,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter'
          - pattern: '/**'
            filters: 'JOINED_FILTERS,-restTokenValidationFilter,-restExceptionTranslationFilter'

# ------------------ Hibernate ------------------
hibernate:
  cache:
    queries: true
    use_second_level_cache: true
    use_query_cache: true
    region:
      factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

info:
  app:
    name: 'tidistock'
    version: '0.1'
    grailsVersion: '5.3.2'
spring:
  jmx:
    unique-names: true
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false
  devtools:
    restart:
      additional-exclude:
        - '*.gsp'
        - '**/*.gsp'
        - '*.gson'
        - '**/*.gson'
        - 'logback.groovy'
        - '*.properties'
# ------------------ Message API ------------------
message:
  api:
    url: "https://cpaas.messagecentral.com/verification/v3/"
    customerId: "C-AB6DD49CF0AE4D0"
    authToken: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJDLUFCNkRENDlDRjBBRTREMCIsImlhdCI6MTc2MjU4MzU5MywiZXhwIjoxOTIwMjYzNTkzfQ.hnaR3GmY6OE5bB5uAbrqM8XPkS3CIKLNEEI6ku-iceeZJRC7rZPYoWaSH42nBxnbsLwtGeSngLLmqPygTCA7NA"


# ------------------ AWS S3 ------------------
aws:
  s3:
    accessKey: 'AKIAQGP656565J7N4P'
    secretKey: 'XOn9QvQ48p6qjr1Jr+a5jD1ydXJTWM31yYbr6565'
    region: 'eu-north-1'
    bucketName: 'tidistock'
    url: 'https://tidistock.s3.amazonaws.com/USERS/'

ipo:
  api:
    url: "https://api.ipoalerts.in/ipos"
    key: "286e4cb62ff6507ed82aa76ae729211e72a8b356205f00b56f556a5868013bb3"
fii:
  api:
    url: "https://www.truedata.com/api/fiidiiTradeReact"



# ------------------ Environments ------------------
environments:
  development:
    market:
      api:
        url: "https://ai.dematbazaar.in/"
        password: "Admin123#"
    razor_pay:
      api_key: 'rzp_test_Rw6UnN3MYKcSGz'
      secret_key: 'mcQPNNzcbMvU2HqtDrgtI5FS'
      webhook_secret: '@nJzgw94cNMRZ2z'
    management:
      endpoints:
        enabled-by-default: true
        web:
          base-path: '/actuator'
          exposure:
            include: '*'
    dataSource:
      dbCreate: update
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tidistock?allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: sigma123
      dialect: org.hibernate.dialect.MySQL8Dialect

  test:
    market:
      api:
        url: "https://ai.dematbazaar.in/"
        password: "Admin123#"
    razor_pay:
      api_key: 'rzp_test_Rw6UnN3MYKcSGz'
      secret_key: 'mcQPNNzcbMvU2HqtDrgtI5FS'
      webhook_secret: '@nJzgw94cNMRZ2z'
    spring:
      management:
        endpoints:
          enabled-by-default: false
    dataSource:
      dbCreate: update
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://tidistock-mysql:3306/tidistock
      username: tidistock
      password: tidistock
      dialect: org.hibernate.dialect.MySQL8Dialect
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
